### ISSUE TITLE
Prevent future email outages by fixing LetsEncrypt SSL autorenewal issues and monitoring expiry dates

### ISSUE THREAD

**Issue by joshuacwnewton** [spinalcordmri/spinalcordmri.github.io#83]
This issue is tangential to https://github.com/spinalcordmri/spinalcordmri.github.io/issues/79. That issue is about monitoring email outages of any kind. However, to mitigate outages specifically related to SSL certificate renewal, we should get to the bottom of why the SSL certificate failed to auto-renew in the first place. 

## 1st outage

The expiry date for the very first cert (first email outage) was:

```console
forum@forum:~$ cd /var/discourse/shared/standalone/ssl_backup_expired_cert
forum@forum:/var/discourse/shared/standalone/ssl_backup_expired_cert$ openssl x509 -enddate -noout -in devforum.spinalcordmri.org.cer
notAfter=Mar 14 23:22:16 2023 GMT
``` 

This seems to line up with when emails began getting dropped:

![image](https://github.com/spinalcordmri/spinalcordmri.github.io/assets/16181459/c45dcd42-7b78-4746-bb88-8464fda6e082)

This outage was caught and fixed on May 11th, 2023. 

## 2nd outage

After renewal, the expiry date for the new cert (i.e. second email outage) was:

```console
forum@forum:/var/discourse/shared/standalone/ssl_backup_expired_cert$ openssl x509 -enddate -noout -in forum.spinalcordmri.org.cer
notAfter=Jul 14 23:22:16 2023 GMT
``` 

This doesn't quite make sense to me, as LetsEncrypt SSL certs should last for [90 days](https://letsencrypt.org/docs/faq/#what-is-the-lifetime-for-let-s-encrypt-certificates-for-how-long-are-they-valid). May 11th + 90 days = August 9th, which is also when the forum began dropping emails a second time:

![image](https://github.com/spinalcordmri/spinalcordmri.github.io/assets/16181459/f2788d0a-a9c6-4cfd-8aba-28c3cf6a8b90)

The second outage was caught and fixed on August 18th, 2023. 

## Next outage

If we check the current cert, we see:

```console
forum@forum:/var/discourse/shared/standalone/ssl_backup_expired_cert$ cd ../ssl
forum@forum:/var/discourse/shared/standalone/ssl$ openssl x509 -enddate -noout -in forum.spinalcordmri.org.cer
notAfter=Oct 7 23:03:14 2023 GMT
```

This is again a bit strange, since August 18th + 90 days = November 16th instead. Still, even if the auto-renewal issues are fixed, we should keep an eye out on these various dates, and perhaps set up some sort of reminder.

**Comment by joshuacwnewton** [comment]
From what I can tell from [the documentation](https://meta.discourse.org/t/set-up-https-support-with-lets-encrypt/40709#how-does-it-work-6), Discourse uses [`acme.sh`](https://github.com/acmesh-official/acme.sh) for cert renewal (as opposed to, say, `certbot`). Plus, setting up Discourse should automatically enable a cron job that will run `acme.sh`:

> At the same time, it adds a cron job that runs a daily cert renewal check. This will automatically renew your cert. Nothing happens if cert has not expired. If the certificate does expire, you’ll get an email about it from Let’s Encrypt at the email address you provided during setup.

I checked our `app.yml` config file, and everything appears to be setup correctly for LetsEncrypt/SSL: 

```yaml
## Uncomment these two lines if you wish to add Lets Encrypt (https)
  - "templates/web.ssl.template.yml"
  - "templates/web.letsencrypt.ssl.template.yml"

## which TCP/IP ports should this container expose?
## If you want Discourse to share a port with another webserver like Apache or nginx,
## see https://meta.discourse.org/t/17247 for details
expose:
  - "80:80"   # http
  - "443:443" # https

[...]

  ## If you added the Lets Encrypt template, uncomment below to get a free SSL certificate
  LETSENCRYPT_ACCOUNT_EMAIL: neuropoly-admin@liste.polymtl.ca
```

Yet, we've never received an email at "neuropoly-admin@liste.polymtl.ca" about a LetsEncrypt expiry. Very curious!
